self.spawn = [=](var& self) -> void {
	self.setVar("tryToFindAndAttackTarget", [=](var& self, double dt) -> bool {
		var targets = self.enemiesInRange(20);
		if (!targets.empty()) {
			var target = targets[0].networkId();
			print("Target Id:");
			print(target);
			var activeTarget = self.getVar("activeTarget");
			print(activeTarget);
			if (activeTarget != target) {
				print("ComparisonDone");
				self.setVar("activeTarget", target);
				self.targeting().target(target, 10, [target](var& targeting) -> void {
					targeting.self().setVar("activeTarget", 0);
					targeting.self().setVar("attacking", true);
					print("ATTACKING VAR: " + to_string(targeting.self().getVar("attacking")));
					auto spine = targeting.self().spine();
					spine.animate("attack", false);
					spine.onEvent.connect("launch", [target, targeting](var& spine, int index, var& eventData) -> void {
						if (eventData.name == "launch") {
							print("LAUNCHING");
							var newMissile = BattleEffectNetworkState(targeting.self().game(), "Missile", targeting.self().networkId());
							newMissile.duration = 1.25;
							newMissile.targetType = TargetType_CREATURE;
							newMissile.targetCreatureId = target;
							auto effect = spawnOnNetwork(newMissile);
							effect.onArrive.connect("Arrive", [=](var& battleEffect) -> void {
								if (battleEffect.targetCreature() != null) {
									print("Damage!");
									battleEffect.targetCreature().changeHealth(-5);
								}
							});
						}
					});
					spine.onEnd.connect("unlock", [targeting](var& spine, int index) -> void {
						print("ATTACK" + spine.track(index).name());
						if (spine.track(index).name() == "attack") {
							print("ATTACK FALSE");
							targeting.self().setVar("attacking", false);
						}
					});
				}, [=](var& targeting) -> void {
					targeting.self().setVar("activeTarget", 0);
				});
			}
			return true;
		}
		return false;
	});

	self.setVar("applyDefaultTarget", [=](var& self) -> void {
		self.targeting().target(self.team().enemyWell(), [=](var& targeting) -> void {
			print(to_string(targeting.self().networkId()) + " made it!");
			targeting.self().fall();
		});
	});

	self.setVar("attacking", false);
	self.setVar("activeTarget", 0);
	self.agent().gridSpeed(10);
};

self.update = [=](var& self, double dt) -> void {
	if (!self.getVar("attacking")) {
		var tryToFindAndAttackTarget = self.getVar("tryToFindAndAttackTarget");
		if (!tryToFindAndAttackTarget(self, dt)) {
			var applyDefaultTarget = self.getVar("applyDefaultTarget");
			applyDefaultTarget(self);
		}
	} else {
		print("Attacking: " + to_string(self.getVar("activeTarget")));
	}
};
